### PR TITLE
fix(185): Wrap buf_del_keymap in pcall()

### PR DESCRIPTION
**Pull request by benjaminchristie**
Wraps buf_del_keymap in pcall(), fixing #185 .

### CODE REVIEW

**Comment by sakhnik** [comment]
Could you please rebase on top of master or merge master in? I'm concerned that the change, as straightforward as this one, fails automatic tests. We'll have to look into that.

**Comment by benjaminchristie** [comment]
Merged master.

**Comment by sakhnik** [comment]
Would you be able to figure out why exactly the test fails?

**Comment by benjaminchristie** [comment]
Fixed and verified tests locally.

**Comment by sakhnik** [comment]
Thanks, I appreciate it!

**Pull request merged**
