### PR TITLE
Keep cursor position, fix #37

### LINKED ISSUE #37: how can can I make the cursor position fixed
[

](url)

I want to see code below and before the cursor. But when I debug,the cursor will be the bottom. Can I have method to control the cursor position? tks.

### PR DESCRIPTION
**Pull request by voldikss**

### CODE REVIEW

**Comment by voldikss** [comment]
CI runs on my forked repo... Maybe it's better to enable CI on `pull_request`?

**Comment by sakhnik** [comment]
I did it in the other branch (https://github.com/sakhnik/nvim-gdb/commit/def0a2c3bef3a867a7cda10420744c8268a31bc6), but it's still there. But no worries, I've fetched your change, all the tests pass.

**Comment by sakhnik** [comment]
Thanks for your contribution!

**Comment by voldikss** [comment]
Thank you for the hard work on the plugin!

**Pull request merged**
