### PR TITLE
Add more autocmds

### PR DESCRIPTION
**Pull request by foonathan**
I used nvim's virtual text feature to show the values of local variables inline in the buffer (if you're interested, I can do a PR but I only have lldb support). But for that I needed more autocmds.

### CODE REVIEW

**Comment by sakhnik** [comment]
Thanks a lot! I'm curious what's that virtual text feature. Could you please share your change? Could you prepare a small demo in https://asciinema.org or alike?

**Comment by foonathan** [comment]
I mean something like this:

Screenshot from 2019-07-02 11-43-53

The values of local variables in the entire current call stack are shown in the buffer, automatically updating when the program stops.

**Comment by sakhnik** [comment]
That's a piece of pure magic! I wasn't aware of that feature until today.

**Comment by foonathan** [comment]
So you want a PR? :D

**Comment by sakhnik** [comment]
Yes, please. Let me assess your feature.

**Pull request merged**
